### ISSUE TITLE
throw error `Failed` in GitHub actions

### ISSUE THREAD

**Issue by fi3ework** [microsoft/vscode-test#61]
workflow file: https://github.com/fi3ework/vscode-antd-rush/blob/master/.github/workflows/test.yml

a failed action: https://github.com/fi3ework/vscode-antd-rush/runs/599819681?check_suite_focus=true

I use vscode-test to test my VSCode extension. But recently it directly throws `Fail` when initializing. The error is throw from here https://github.com/microsoft/vscode-test/blob/master/lib/runTest.ts#L134, but I don't know why it throw. I can pass the test on my Macbook Pro(masOS 10.14.6, nodejs v10.16.0). I can't  reproduce it on my own computer no matter how. 🤦‍♂️

Please help me or give a hint where I might missed or wrong. Thank you very much. 🙏🏻

Here's the failed screenshot 👇

![image](https://user-images.githubusercontent.com/12322740/79696137-58dc3100-82ad-11ea-8fe2-49fa48a80d9a.png)

and workflow file (pasted for better preview)

```yml
name: Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        node: [10, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn - install & compile
        run: |
          yarn
          yarn run compile
          yarn run compile-test
      - name: Run headless tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
```

Also asked in [community forum](https://github.community/t5/GitHub-Actions/vscode-test-throw-unexpected-error-Fail/m-p/54658#M9245)
